<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     assignfeedback_aif *
 * @category    string
 * @copyright   2024 Marcus Green
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// General settings.
$string['default_help'] = 'The plugin will be enabled by default when a new assignment is created';
$string['enabled'] = "Enabled";
$string['enabled_help'] = 'Enable the AI Feedback plugin. <br>
Note: To generate AI feedback from file submissions, please enable a document converter supporting text conversions like Google Drive.';
$string['enabledbydefault'] = 'Enabled by default';
$string['file'] = 'Prompt file';
$string['file_help'] = 'Uploading prompts through a text file is a long term goal';
$string['pluginname'] = 'AI Assisted Feedback';
$string['prompt'] = 'Prompt';
$string['prompt_help'] = 'Prompt that will be sent to the remote LLM (E.G ChatGPT)';
$string['prompt_setting'] = 'Analyse the grammar in this text';
$string['prompt_text'] = 'The default prompt that will be added to a new instance';

// AI Backend settings.
$string['backends'] = 'AI backend system';
$string['backends_text'] = 'Core AI system was introduced with Moodle 4.5. Local AI manager provides advanced features like usage quotas, role-based configuration and purpose-specific AI tools.';
$string['localaimanager'] = 'Local AI manager';
$string['coreaisubsystem'] = 'Core AI subsystem';
$string['purpose'] = 'AI purpose';
$string['purpose_text'] = 'The purpose identifier used by local_ai_manager to select the appropriate AI tool. Common values: feedback, translate, summarise.';

// Prompt template settings.
$string['prompttemplate'] = 'Prompt template';
$string['prompttemplate_text'] = 'The structured template for building the AI prompt. Use placeholders: {{submission}}, {{rubric}}, {{prompt}}, {{assignmentname}}, {{language}}. These will be replaced with actual values.';
$string['defaultprompttemplate'] = '=== ROLE ===
You are an experienced teacher providing constructive feedback on student submissions.

=== ASSIGNMENT ===
{{assignmentname}}

=== GRADING CRITERIA ===
{{rubric}}

=== TEACHER INSTRUCTIONS ===
{{prompt}}

=== STUDENT SUBMISSION ===
{{submission}}

=== OUTPUT INSTRUCTIONS ===
Provide detailed, constructive feedback that helps the student improve.
Focus on both strengths and areas for improvement.
Be encouraging but honest.

=== LANGUAGE ===
Respond in {{language}}.';

// Disclaimer settings.
$string['disclaimer'] = 'Disclaimer';
$string['disclaimer_text'] = 'Text appended to each AI response indicating feedback is from a Large Language Model and not a human.';
$string['defaultdisclaimer'] = '(This feedback was generated by an AI system and reviewed by your teacher.)';
$string['translatedisclaimer'] = 'Translate disclaimer';
$string['translatedisclaimer_text'] = 'If enabled, the disclaimer will be translated to the user\'s language using the AI system.';

// Task strings.
$string['processfeedbactask'] = 'Process feedback task';
$string['processfeedbacktask'] = 'Taskprocessfeedback';
$string['taskprocessfeedbackrubric'] = 'Taskprocessfeedbackrubric';

// Auto-generate settings.
$string['autogenerate'] = 'Generate feedback automatically on submission';
$string['autogenerate_help'] = 'If enabled, AI feedback will be automatically generated when a student submits their assignment. The feedback generation runs as a background task and may take a few minutes to complete.';

// Batch operation strings.
$string['batchoperationconfirmgeneratefeedbackai'] = 'Generate AI feedback for one or all selected users?';
$string['batchoperationgeneratefeedbackai'] = 'Generate AI feedback';
$string['generatefeedbackai'] = 'Generate AI feedback';
$string['batchoperationconfirmdeletefeedbackai'] = 'Delete AI feedback for one or all selected users?';
$string['batchoperationdeletefeedbackai'] = 'Delete AI feedback';
$string['deletefeedbackai'] = 'Delete AI feedback';
$string['processfeedbackainotify'] = 'Please wait for the cron to run to process the AI Feedback';

// Error strings.
$string['err_retrievingfeedback'] = 'Error retrieving feedback from AI tool: {$a}';
$string['err_retrievingfeedback_checkconfig'] = 'Unable to retrieve feedback. AI system configuration might be wrong, please contact your administrator.';
$string['err_invalidbackend'] = 'Invalid AI backend configured.';
$string['err_translationfailed'] = 'Translation failed, using original text.';

// Regenerate button strings.
$string['regenerate'] = 'Regenerate AI feedback';
$string['regenerating'] = 'Regenerating...';
$string['regenerate_queued'] = 'AI feedback regeneration has been queued. Please wait for the background task to complete.';

// Privacy strings.
$string['privacy:aipath'] = 'AI Feedback';
$string['privacy:metadata:assignmentid'] = 'Assignment ID';
$string['privacy:metadata:aitext'] = 'AI Feedback text.';
$string['privacy:metadata:tablesummary'] = 'This stores AI feedback made by the AI proivders as feedback for the student on their submission.';
