<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     assignfeedback_aif
 * @category    string
 * @copyright   2024 Marcus Green
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['ainavailable'] = 'AI backend is not available for this purpose';
$string['autogenerate'] = 'Generate feedback automatically on submission';
$string['autogenerate_help'] = 'If enabled, AI feedback will be automatically generated when a student submits their assignment. The feedback generation runs as a background task and may take a few minutes to complete.<br><br><strong>Practice mode:</strong> When the assignment marking workflow is <strong>disabled</strong>, students see the AI feedback immediately after generation without teacher review. A separate disclaimer is shown to indicate the feedback has not been reviewed.<br><br><strong>Teacher-reviewed mode:</strong> When the assignment marking workflow is <strong>enabled</strong>, students only see the AI feedback after the teacher releases the grade. This allows teachers to review and edit the feedback before students see it.';
$string['backends'] = 'AI backend system';
$string['backends_text'] = 'Core AI system was introduced with Moodle 4.5. Local AI manager provides advanced features like usage quotas, role-based configuration and purpose-specific AI tools.';
$string['batchoperationconfirmdeletefeedbackai'] = 'Delete AI feedback for one or all selected users?';
$string['batchoperationconfirmgeneratefeedbackai'] = 'Generate AI feedback for one or all selected users?';
$string['batchoperationdeletefeedbackai'] = 'Delete AI feedback';
$string['batchoperationgeneratefeedbackai'] = 'Generate AI feedback';
$string['cachecleanupdelay'] = 'Cache cleanup delay (days)';
$string['cachecleanupdelay_text'] = 'Extracted file content is cached to avoid repeated AI calls. Cached entries not accessed within this number of days will be cleaned up. Set to 0 to disable cleanup.';
$string['coreaisubsystem'] = 'Core AI subsystem';
$string['default_help'] = 'The plugin will be enabled by default when a new assignment is created';
$string['defaultdisclaimer'] = '(This feedback was generated by an AI system and reviewed by your teacher.)';
$string['defaultpracticedisclaimer'] = '(This feedback was generated by an AI system for self-study purposes. It has NOT been reviewed or approved by a teacher. Use it as a learning aid, but be aware that AI feedback may contain errors.)';
$string['defaultprompttemplate'] = '=== ROLE ===
You are an experienced teacher providing constructive feedback on student submissions.

=== ASSIGNMENT ===
{{assignmentname}}

=== GRADING CRITERIA ===
{{rubric}}

=== TEACHER INSTRUCTIONS ===
{{prompt}}

=== STUDENT SUBMISSION ===
{{submission}}

=== OUTPUT INSTRUCTIONS ===
Provide detailed, constructive feedback that helps the student improve.
Focus on both strengths and areas for improvement.
Be encouraging but honest.

Format your response in strict Markdown:
- Use ## for section headings.
- Use "1. " for numbered lists (NOT "1)").
- Use "- " for bullet lists.
- Always leave a blank line before and after headings, lists, and code/math blocks.
- Use **bold** and *italic* for emphasis.
- For math equations use LaTeX: inline with $$ ... $$ and display blocks with \\[ ... \\].

=== LANGUAGE ===
Respond in {{language}}.';
$string['deletefeedbackai'] = 'Delete AI feedback';
$string['disclaimer'] = 'Disclaimer';
$string['disclaimer_text'] = 'Text appended to each AI response indicating feedback is from a Large Language Model and not a human.';
$string['enabled'] = 'Enabled';
$string['enabled_help'] = 'Enable the AI Feedback plugin. <br>
Note: Images and PDFs are automatically converted to text using AI image-to-text (ITT). A document converter (e.g. Google Drive) is used as fallback for DOCX and other document formats.';
$string['enabledbydefault'] = 'Enabled by default';
$string['enableexpertmode'] = 'Enable expert mode';
$string['enableexpertmode_text'] = 'When enabled, shows an "Expert mode template" button in the assignment settings, allowing teachers to use the full prompt template with all placeholders directly.';
$string['err_invalidbackend'] = 'Invalid AI backend configured.';
$string['err_retrievingfeedback'] = 'Error retrieving feedback from AI tool: {$a}';
$string['err_retrievingfeedback_checkconfig'] = 'Unable to retrieve feedback. AI system configuration might be wrong, please contact your administrator.';
$string['err_translationfailed'] = 'Translation failed, using original text.';
$string['expertmodeconfirm'] = 'This will replace the current prompt with the expert mode template.<br><br><strong>What is expert mode?</strong><br>In expert mode, you have full control over the entire AI prompt. The admin template is ignored and your prompt is sent directly to the AI.<br><br><strong>Available placeholders:</strong><ul><li><code>{{submission}}</code> - The student\'s submission text (required to activate expert mode)</li><li><code>{{rubric}}</code> - The rubric criteria (if configured)</li><li><code>{{assignmentname}}</code> - The assignment name</li><li><code>{{language}}</code> - The user\'s language for the response</li></ul><strong>Note:</strong> The presence of <code>{{submission}}</code> in your prompt activates expert mode. Without it, your prompt is inserted into the admin template at the <code>{{prompt}}</code> placeholder.<br><br>Continue?';
$string['file'] = 'Prompt file';
$string['file_help'] = 'Uploading prompts through a text file is a long term goal';
$string['generatefeedbackai'] = 'Generate AI feedback';
$string['localaimanager'] = 'Local AI manager';
$string['pluginname'] = 'AI Assisted Feedback';
$string['practicedisclaimer'] = 'Practice mode disclaimer';
$string['practicedisclaimer_text'] = 'Disclaimer appended to AI feedback in practice mode (autogenerate without marking workflow). This text indicates the feedback was not reviewed by a teacher.';
$string['privacy:aipath'] = 'AI Feedback';
$string['privacy:metadata:aitext'] = 'AI Feedback text.';
$string['privacy:metadata:assignmentid'] = 'Assignment ID';
$string['privacy:metadata:tablesummary'] = 'This stores AI feedback made by the AI providers as feedback for the student on their submission.';
$string['processfeedbacktask'] = 'Process AI feedback';
$string['prompt'] = 'Prompt';
$string['prompt_help'] = 'Prompt that will be sent to the remote LLM (E.G ChatGPT)';
$string['prompt_setting'] = 'Analyse the grammar in this text';
$string['prompt_text'] = 'The default prompt that will be added to a new instance';
$string['prompttemplate'] = 'Prompt template';
$string['prompttemplate_text'] = 'The structured template for building the AI prompt. Use placeholders: {{submission}}, {{rubric}}, {{prompt}}, {{assignmentname}}, {{language}}. These will be replaced with actual values.';
$string['purposeplacedescription_feedback'] = 'Generating AI feedback on student submissions';
$string['purposeplacedescription_itt'] = 'Analysing submitted images for AI feedback';
$string['regenerate'] = 'Regenerate AI feedback';
$string['regenerate_queued'] = 'AI feedback regeneration has been queued. Please wait for the background task to complete.';
$string['regenerating'] = 'Regenerating...';
$string['taskcleanupcache'] = 'Clean up expired file content cache';
$string['taskprocessfeedback'] = 'Process AI feedback';
$string['useexpertmodetemplate'] = 'Expert mode template';
