// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * AMD module for the teacher-facing AI feedback progress widget.
 *
 * Polls the get_assignment_feedback_summary webservice every 10 seconds
 * and updates the widget with current counts and progress bars.
 * Stops polling when all feedback is completed or no tasks are pending.
 *
 * @module     assignfeedback_aif/feedbacksummary
 * @copyright  2026 ISB Bayern
 * @author     Andreas Wagner
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

import Ajax from 'core/ajax';
import Log from 'core/log';
import Templates from 'core/templates';
import {get_string as getString} from 'core/str';

/** @var {number} POLL_INTERVAL_MS Polling interval in milliseconds. */
const POLL_INTERVAL_MS = 10000;

/**
 * Controller for one feedback summary widget instance.
 */
class FeedbackSummaryController {
    /** @var {string} widgetSelector Selector for the widget root element. */
    widgetSelector;

    /** @var {number|null} assignmentId Assignment id for this widget. */
    assignmentId = null;

    /** @var {object|null} strings Cached localized strings. */
    strings = null;

    /** @var {number|null} timer Active polling timer. */
    timer = null;

    /**
     * Constructor.
     *
     * @param {string} selector Widget selector generated by the template.
     */
    constructor(selector) {
        this.widgetSelector = selector;
    }

    /**
     * Initialize and start polling for this widget.
     */
    async start() {
        const widget = document.querySelector(this.widgetSelector);
        if (!widget) {
            return;
        }

        const assignmentId = Number(widget.dataset.assignmentid);
        if (!Number.isInteger(assignmentId) || assignmentId <= 0) {
            return;
        }

        this.assignmentId = assignmentId;
        this.strings = await this.loadStrings();

        const shouldContinue = await this.updateWidget();
        if (shouldContinue) {
            this.scheduleNextPoll();
        }
    }

    /**
     * Load all required language strings.
     *
     * @returns {object} Object with named string properties.
     */
    async loadStrings() {
        const keys = [
            'widgetcompleted',
            'widgetpending',
            'widgeterrors',
            'widgetnotstarted',
            'widgetcounts',
            'widgetsystemicerror',
            'widgetretryall',
        ];
        const values = await Promise.all(
            keys.map(key => getString(key, 'assignfeedback_aif'))
        );
        const result = {};
        keys.forEach((key, i) => {
            result[key] = values[i];
        });
        return result;
    }

    /**
     * Queue the next poll cycle.
     */
    scheduleNextPoll() {
        this.stop();
        this.timer = setTimeout(async() => {
            const shouldContinue = await this.updateWidget();
            if (shouldContinue) {
                this.scheduleNextPoll();
            }
        }, POLL_INTERVAL_MS);
    }

    /**
     * Stop polling for this widget instance.
     */
    stop() {
        if (this.timer) {
            clearTimeout(this.timer);
            this.timer = null;
        }
    }

    /**
     * Build the widget DOM id.
     *
     * @param {number} assignmentId The assignment instance id.
     * @returns {string} DOM id for the widget root node.
     */
    getWidgetId(assignmentId) {
        return 'assignfeedback-aif-summary-widget-' + assignmentId;
    }

    /**
     * Build the widget CSS selector.
     *
     * @param {number} assignmentId The assignment instance id.
     * @returns {string} CSS selector for the widget root node.
     */
    getWidgetSelector(assignmentId) {
        return '#' + this.getWidgetId(assignmentId);
    }

    /**
     * Build template context from webservice data.
     *
     * @param {object} data Summary payload from the webservice.
     * @returns {object} Template context.
     */
    buildTemplateContext(data) {
        const totalsubmissions = Number(data.totalsubmissions) || 0;
        const completed = Number(data.completed) || 0;
        const errors = Number(data.errors) || 0;
        const pending = Number(data.pending) || 0;
        const notstarted = Number(data.notstarted) || 0;
        const haspending = Boolean(data.haspending);
        const activepending = pending + (haspending ? notstarted : 0);

        const systemicerrors = (data.systemicerrors || []).map((error) => ({
            message: error.message,
            counttext: this.strings.widgetsystemicerror.replace('{$a}', error.count),
        }));

        const getPercentage = (value) => {
            if (totalsubmissions <= 0) {
                return '0.0';
            }
            return (value / totalsubmissions * 100).toFixed(1);
        };

        return {
            assignmentid: this.assignmentId,
            widgetid: this.getWidgetId(this.assignmentId),
            widgetselector: this.getWidgetSelector(this.assignmentId),
            showwidget: totalsubmissions > 0,
            hassummary: totalsubmissions > 0,
            countstext: completed + ' / ' + totalsubmissions,
            barcompleted: getPercentage(completed),
            barpending: getPercentage(activepending),
            barerrors: getPercentage(errors),
            hasdetails: activepending > 0 || errors > 0 || completed > 0,
            hasactivepending: activepending > 0,
            activependingcount: activepending,
            pendinglabel: this.strings.widgetpending,
            haserrors: errors > 0,
            errorscount: errors,
            errorslabel: this.strings.widgeterrors,
            hascompleted: completed > 0,
            completedcount: completed,
            completedlabel: this.strings.widgetcompleted,
            systemicerrors: systemicerrors,
            hassystemicerrors: systemicerrors.length > 0,
        };
    }

    /**
     * Fetch summary data and replace widget markup.
     *
     * @returns {boolean} True if polling should continue.
     */
    async updateWidget() {
        try {
            const widget = document.querySelector(this.widgetSelector);
            if (!widget) {
                return false;
            }

            const data = await Ajax.call([{
                methodname: 'assignfeedback_aif_get_assignment_feedback_summary',
                args: {assignmentid: this.assignmentId},
            }])[0];

            const context = this.buildTemplateContext(data);
            const {html, js} = await Templates.renderForPromise(
                'assignfeedback_aif/feedback_summary_widget',
                context
            );
            await Templates.replaceNode(widget, html, js);

            // New markup executes init() again, so this instance can stop here.
            this.stop();
            return false;
        } catch (error) {
            Log.debug('assignfeedback_aif/feedbacksummary: poll error.');
            Log.debug(error);
            return false;
        }
    }
}

/**
/**
 * Initialize one widget controller instance.
 *
 * @param {string} selector Widget selector generated by the template.
 */
export const init = (selector) => {
    if (!selector) {
        Log.debug('assignfeedback_aif/feedbacksummary: missing widget selector.');
        return;
    }

    const controller = new FeedbackSummaryController(selector);
    controller.start();
};


